name: flutter_base
description: flutter_base_Project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #------------------------------- Network -----------------------------------------------
  dio: ^5.4.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  flutter_offline: ^3.0.1

  #------------------------------- FireBase -----------------------------------------------
  flutter_local_notifications: ^17.1.2
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1

  #------------------------------- State Managment -----------------------------------------------
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  multiple_result: ^5.1.0

  #------------------------------- Local Storage -----------------------------------------------
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  #------------------------------- Language -----------------------------------------------
  easy_localization: ^3.0.7
  watcher: ^1.1.0
  #------------------------------- UI_Packages -----------------------------------------------
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  file_picker: ^8.0.5
  flutter_colorpicker: ^1.1.0
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.3.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  intl: 0.19.0
  path: 1.9.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  pinput: ^5.0.0
  share_plus: ^9.0.0
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  svg_flutter: ^0.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/
    - assets/lottie/
    - assets/translations/
