name: flutter_base
description: flutter_base Project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dotted_border: ^2.1.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  flutter_local_notifications: ^16.3.0
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  form_builder_validators: ^9.1.0

  get_it: ^7.6.6
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: any
  multiple_result: ^5.1.0
  path: any
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  pinput: ^3.0.1
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.1.0
  svg_flutter: ^0.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/ 
    - assets/lottie/ 
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
