name: flutter_base
description: flutter_base_Project.
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #------------------------------- Network -----------------------------------------------
  dio: ^5.4.1
  cached_network_image: ^3.3.1
  # internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.2.5
  flutter_offline: ^3.0.1

  #------------------------------- FireBase -----------------------------------------------
  flutter_local_notifications: ^17.0.0
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20

  #------------------------------- State Managment -----------------------------------------------
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  multiple_result: ^5.1.0

  #------------------------------- Local Storage -----------------------------------------------
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  #------------------------------- Language -----------------------------------------------
  easy_localization: ^3.0.5

  #------------------------------- UI_Packages -----------------------------------------------
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  file_picker: ^6.2.0
  flutter_colorpicker: ^1.0.3
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.7
  intl: any
  path: 1.9.0
  path_provider: ^2.1.2
  photo_view: ^0.14.0
  pinput: ^4.0.0
  share_plus: ^7.2.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  svg_flutter: ^0.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/fonts/
    - assets/lottie/
    - assets/translations/
